#include "Includes.h"

HANDLE aConsole = GetStdHandle(STD_OUTPUT_HANDLE);

void loadinganimation() {
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SICKOWARE       X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                                          LOADING |            \n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SICKOWARE       X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                                          LOADING /            \n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SICKOWARE       X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                                          LOADING -            \n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SICKOWARE       X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                                          LOADING \            \n";
	Sleep(80);
}
void WelcomeScreen() {
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           W                          X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WE                         X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WEL                        X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELC                       X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCO                      X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOM                     X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME                    X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME T                  X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X            WELCOME TO                X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO S               X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SI              X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SIC             X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SICK            X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SICKOW          X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SICKOWA         X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SICKOWAR        X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(80);
	system("cls");
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SICKOWARE       X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(500);
	for (int i = 0; i < 10; i++) {
		loadinganimation();
	}
}
void crossScreen() {
	SetConsoleTextAttribute(aConsole, 4);
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	Sleep(1500);
	system("cls");
}
void MainText() {
	SetConsoleTextAttribute(aConsole, 4);
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        X                                      X\n";
	cout << "                                        X           WELCOME TO SICKOWARE       X\n";
	cout << "                                        X                                      X\n";
	cout << "                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n";
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        X HWID: 38BC1A     USER:" << "s" <<"        X\n";
	cout << "                                        X ACCESS: 12/20    UPDATE: 02-08-21    X\n";
	cout << "                                        X INJECTOR: "<< injectorMethod <<"      SPOOFER: NONE       X\n";
	cout << "\n";

}
void menuAnimation() {
	SetConsoleTextAttribute(aConsole, 4);
	MainText();
	cout << "                                        \n";
	cout << "                                        \n";
	cout << "                                        X HWID: 38BC1A     USER:" << "s" << "      X\n";
	cout << "                                        X ACCESS: 12/20    UPDATE: 02-08-21    X\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X#######################################\n";
	cout << "                                        X#######################################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X H#####################################\n";
	cout << "                                        X A#####################################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X HW####################################\n";
	cout << "                                        X AC####################################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X HWI###################################\n";
	cout << "                                        X ACC###################################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X HWID##################################\n";
	cout << "                                        X ACCE##################################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X HWID:#################################\n";
	cout << "                                        X ACCES#################################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X HWID: 3###############################\n";
	cout << "                                        X ACCESS: 2##############################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X HWID: 3B##############################\n";
	cout << "                                        X ACCESS: 20#############################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X HWID: 3B1#############################\n";
	cout << "                                        X ACCESS: 20/############################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X HWID: 3B12############################\n";
	cout << "                                        X ACCESS: 20/2###########################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X HWID: 3B12C###########################\n";
	cout << "                                        X ACCESS: 20/20##########################\n";
	Sleep(150);
	system("cls");

	cout << "\n";
	cout << "\n";
	MainText();
	cout << "\n";
	cout << "\n";
	cout << "                                        X HWID: 3B12CD##########################\n";
	cout << "                                        X ACCESS: 20/20 #########################\n";
	Sleep(150);
	system("cls");
}